Repository ABDERRAOUFMERAZKA/Cest_Pret_De_Chez_Vous, pull requests merged in 2019-11, with the labels that each got.

#7 As a dev i want to connect app to firebase/FireStore
  .gitignore
  android/app/build.gradle
  android/build.gradle
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  lib/src/Menu/Menu.dart
  pubspec.yaml
Labels: Approved

#12 As a dev i want to switch login from twitter to firebase
  assets/google_icon.png
  ios/Podfile.lock
  lib/login_value.dart
  lib/src/Login/widget/Login.dart
  lib/src/Menu/Menu.dart
  lib/styles.dart
  pubspec.yaml
Labels: Ready For Review

#13 [ WIP Refacto ] imports errors
  lib/Navigation/Navigation.dart
  lib/src/Favorite.dart
  lib/src/Home.dart
  lib/src/Menu.dart
  lib/src/Menu/Menu.dart
  lib/src/Search.dart
  lib/src/display_ads/model/ad.dart
  lib/src/display_ads/model/user.dart
  lib/src/display_ads/view/favorites.dart
  lib/src/display_ads/view/home.dart
  lib/src/display_ads/view/my_ads.dart
  lib/src/display_ads/view/search.dart
  lib/src/login/login.dart
  lib/src/login/presenter/login.dart
  lib/src/login/services/manage_auth.dart
  lib/src/login/view/login.dart
  lib/src/my_ad.dart
  lib/utils/string_verifier.dart
  lib/welcome.dart
Labels: WIP, refacto

#17 As a dev i want to add verification page to login use case
  lib/src/account_settings/presenter/login.dart
  lib/src/login/view/mail_validation.dart
  lib/welcome.dart
Labels: Approved, Do not merge

#18 As a dev i want to revert print line
  lib/src/login/view/mail_validation.dart
Labels: Approved, bug

#20 As a dev create search widget
  ios/Podfile.lock
  lib/Navigation/Navigation.dart
  lib/src/display_ads/presenter/display_ads.dart
  lib/src/display_ads/service/retrieve_ads.dart
  lib/src/display_ads/view/Search.dart
  lib/src/display_ads/view/add_ads.dart
  pubspec.yaml
Labels: Approved

#35 add display details ad
  lib/src/display_ads/view/ad_details.dart
  lib/src/display_ads/view/widget/ad_in_list.dart
Labels: Ready For Review
