Repository ABDERRAOUFMERAZKA/Cest_Pret_De_Chez_Vous, pull requests merged in 2019-12, with the labels that each got.

#42 [ Refacto ] view model for each (+/-) view
  lib/src/display_ads/service/retrieve_ads.dart
  lib/src/display_ads/utils/filter_ads.dart
  lib/src/display_ads/view/favorites.dart
  lib/src/display_ads/view/home.dart
  lib/src/display_ads/view/my_ads.dart
  lib/src/display_ads/view/search.dart
  lib/src/display_ads/view/widget/ad_in_list.dart
  lib/src/display_ads/view_model/ads_around_view_model.dart
  lib/src/display_ads/view_model/current_user_ads_view_model.dart
  lib/src/display_ads/view_model/display_ads_view_model.dart
  lib/src/display_ads/view_model/favorite_ads_view_model.dart
  lib/utils/list_utils.dart
  lib/welcome.dart
Labels: Ready For Review, refacto

#44 As a dev i want to update pop up of post ad
  lib/src/post_ads/view/add_ad.dart
  lib/src/post_ads/view/widgets/show_dialog_popup.dart
  lib/src/post_ads/view_model/post_ad_view_model.dart
Labels: Approved

#46 [ Fix ] call with eric
  .gitignore
  lib/navigation/navigation.dart
  lib/src/account_settings/services/manage_auth.dart
  lib/src/account_settings/view/mail_validation.dart
  lib/src/account_settings/view/menu.dart
  lib/src/account_settings/view_model/login_view_model.dart
  lib/src/display_ads/model/ad.dart
  lib/src/display_ads/model/ad.g.dart
  lib/src/display_ads/service/ads_around.dart
  lib/src/display_ads/service/ads_from_user.dart
  lib/src/display_ads/service/favorite_ads.dart
  lib/src/display_ads/service/retrieve_ads.dart
  lib/src/display_ads/view/ad_details.dart
  lib/src/display_ads/view/favorites.dart
  lib/src/display_ads/view/home.dart
  lib/src/display_ads/view/my_ads.dart
  lib/src/display_ads/view/widget/ad_in_list.dart
  lib/src/display_ads/view_model/ads_around_view_model.dart
  lib/src/display_ads/view_model/current_user_ads_view_model.dart
  lib/src/display_ads/view_model/display_ads_view_model.dart
  lib/src/display_ads/view_model/favorite_ads_view_model.dart
  lib/src/menu/menu.dart
  lib/src/post_ads/model/ad.dart
  lib/src/post_ads/model/ad.g.dart
  lib/src/post_ads/services/post_ad_services.dart
  lib/src/post_ads/view_model/post_ad_view_model.dart
  lib/utils/enum_utils.dart
  lib/utils/list_utils.dart
  lib/utils/string_utils.dart
  lib/utils/string_verifier.dart
  lib/welcome.dart
  pubspec.yaml
Labels: refacto
